Update to new organization of warc2zim.
openzim/zimit pull request #262
Opened 2024-01-08 15:34 UTC by mgautierfr

Older `warc2zim` method is now named `main`.

2024-01-08 17:33 UTC, rgaudin requested changes
hum, this should:

- include a custom workflow to publish on a separate `:zimit2` tag
- install from warc2zim's zimit2 git branch
- target a `zimit2` branch and not `main`

2024-01-09 07:09 UTC, benoit74 commented
And obviously fix the tests 😉

2024-01-12 11:30 UTC, mgautierfr commented
This PR is not especially relative to warc2zim2. It addapts to a API change in https://github.com/openzim/warc2zim/pull/129 which has been merged on main.

The warc2zim's `warc2zim2` branch obviously need to be used to be tested but it's not introducing a api change.

So I prefer targeting `warc2zim2` branch in another PR. (Which should be pretty easy once the following question has been answered)

What is the best way to test the main(/PR) branch o zimit with the main branch of warc2zim ?

The CI is mainly building the docker which is "publication" oriented and so fixes a specific version of warc2zim (https://github.com/openzim/zimit/blob/main/Dockerfile#L11)

Should I create a new dockerfile ? Should the CI not use the docker file ?


> And obviously fix the tests 😉

Test should not be fixed if we target only the `main` branch of `warc2zim`.

2024-01-12 11:53 UTC, benoit74 commented
You are right, currently, we cannot test a new zimit version based on unreleased warc2zim.

I think the only way forward is to modify the Dockerfile so that it can install an unreleased warc2zim (directly from the source code). And this could then be reverted once everything has settled. 

@rgaudin WDYT?

2024-01-12 22:01 UTC, rgaudin commented
> You are right, currently, we cannot test a new zimit version based on unreleased warc2zim.
> 
> I think the only way forward is to modify the Dockerfile so that it can install an unreleased warc2zim (directly from the source code). And this could then be reverted once everything has settled.
> 
> @rgaudin WDYT?

That's what we already agreed on doing, right? That's also how we are used to do here in-between warc2zim releases… See https://github.com/openzim/zimit/commit/2be55625539c98d3dffd665094a1b6cdac3dd3f5 for instance

2024-01-13 14:21 UTC, kelson42 commented
* Most of the discussion is out-of-topic here and has anyway been already made during the weekly meeting, a week ago.
* @mgautierfr Please [follow review comment of Benoît](https://github.com/openzim/zimit/pull/262#issuecomment-1882519038) so we can complete the review and merge
* Other discussion should better take part of [appropriate ticket ](https://github.com/openzim/zimit/issues/193)(or create a new one dedicated to this).

2024-01-14 09:41 UTC, mgautierfr commented
New commit now use the main version of warc2zim.

As said, this PR adapt to `main` branch of warc2zim. No to the `warc2zim2` branch.

2024-01-15 06:58 UTC, benoit74 approved these changes
LGTM, I just updated the CHANGELOG as well

2024-01-15 06:59 UTC, merged