Replace shell script with python zimit.py + crawl dedup improvements
openzim/zimit pull request #29
Opened 2020-10-16 19:03 UTC by ikreymer

Using python zimit.py for arg parsing + warc2zim calls as suggested in #28. Should fix:
- #18, #28 - arg parsing now handled in python, no shell
- #25 - better handling of interrupt signals, should shutdown gracefully.
- crawler.js now only handles crawling (may be moved to separate project later).

Also includes crawling update to improve cacheing/reduce disk usage:
- Using latest version of pywb, which deduplicates all URLs (using Redis), so duplicates are never stored in WARCs, should reduce disk space.
- Forces browser cacheing on existing urls to reduce load

2020-10-16 20:00 UTC, ikreymer commented
I don't know how to disable the partial path CodeFactor errors (tried with config file), they don't apply here since this is designed to run in a container with known executables.

2020-10-19 15:16 UTC, rgaudin requested changes
Some questions, couple issues. I've fixed the partial paths thing.

2020-10-19 16:20 UTC, ikreymer commented on Dockerfile
> +RUN pip install git+https://github.com/webrecorder/pywb@patch-work
Yes, I can make it be `@develop` but its not quite ready for release there.., can update when its out in the next version of pywb.

2020-10-19 16:21 UTC, rgaudin commented on Dockerfile
> +RUN pip install git+https://github.com/webrecorder/pywb@patch-work
No it's ok, just wanted to be sure

2020-10-19 16:24 UTC, ikreymer commented on crawler.js
> +    "--no-sandbox"
This allows running chrome as root user. It is not necessarily ideal in general, but I think fine in this scenario, and given the constraints of only command-line options. The other main solution is to run with a custom security profile, which you'd need to store on zimfarm outside docker, eg:
https://github.com/armbues/chrome-headless/blob/master/README.md

But maybe worth reexamining once other issues are fixed.

2020-10-19 16:25 UTC, ikreymer commented on zimit.py
> +    parser.add_argument("-u", "--url", help="The URL to start crawling from")
Ok, yeah, probably it should be handled in warc2zim itself.. I'll add a quick PR there.

2020-10-19 16:25 UTC, ikreymer commented on zimit.py
> +        default=90000,
Sure

2020-10-19 16:40 UTC, ikreymer commented on zimit.py
> +        help="The scope of current page that should be included in the crawl (defaults to the domain of URL)",
It's actually the other way now. I think from crawling perspective, it makes more sense that if you have `--url http://domdom.tld/category1/start.html`, the scope is`http://domdom.tld/category1/`.
If you want it to be the whole domain you'd add `--scope http://domdom.tld`. This seemed like a better default, but can change it the other way if you'd prefer that..

One use case for this is for example `https://journals.openedition.org/bibnum/`, where you don't expect to crawl all of `https://journals.openedition.org/` when you specify `--url https://journals.openedition.org/bibnum/`

I think its good to err on the side of more conservative crawling scope, and specify a more broader one explicitly.

2020-10-19 16:40 UTC, ikreymer commented on zimit.py
> +    parser.add_argument(
Only pages

2020-10-19 16:42 UTC, ikreymer commented on zimit.py
> +    warc_files = glob.glob(
I don't think the list will be big enough to cause any issues, even if hundreds of warcs.
This list is also passed to warc2zim for iteration. We could support passing a directory of warcs in warc2zim instead then. Do you prefer that?

2020-10-19 16:44 UTC, rgaudin commented on zimit.py
> +        help="The scope of current page that should be included in the crawl (defaults to the domain of URL)",
Agrees. Help text should be adjusted then.

2020-10-19 16:45 UTC, rgaudin commented on zimit.py
> +    warc_files = glob.glob(
yeah I think it'd make more sense actually.

2020-10-19 16:59 UTC, ikreymer commented on zimit.py
> +    res = warc2zim(warc2zim_args + warc_files)
i think was checking it before, can change.

2020-10-19 17:01 UTC, ikreymer commented on zimit.py
> +    temp_root_dir = tempfile.mkdtemp(dir=zimit_args.output, prefix=".tmp")
Hm, pathlib doesn't have a mkdir (and the comment is out of date, no longer adjusting permissions will fix)

2020-10-19 17:08 UTC, rgaudin commented on zimit.py
> +    temp_root_dir = tempfile.mkdtemp(dir=zimit_args.output, prefix=".tmp")
I meant wrapping it in a Path() as mkdtemp returns a string and we try to always use pathlib for paths

2020-10-19 17:08 UTC, rgaudin commented on zimit.py
> +    res = warc2zim(warc2zim_args + warc_files)
ok

2020-10-19 19:44 UTC, ikreymer commented on zimit.py
> +    parser.add_argument("-u", "--url", help="The URL to start crawling from")
Handled in warc2zim

2020-10-20 08:08 UTC, rgaudin approved these changes

2020-10-20 08:08 UTC, merged